import type { ServerConfig } from "../config";

export function createTestConfig(
  overrides: Partial<ServerConfig> = {},
): ServerConfig {
  return {
    API_HOST: "127.0.0.1",
    API_PORT: 8787,
    WEB_ORIGIN: "http://127.0.0.1:4173",
    API_DOCS_ENABLED: true,
    RATE_LIMIT_MAX: 120,
    RATE_LIMIT_WINDOW_MS: 60_000,
    MARKET_MODE: "mock",
    MARKET_DATA_PROVIDER: "mock",
    MARKET_TICK_MS: 1000,
    MARKET_DATA_TIMEOUT_MS: 15_000,
    MARKET_SYMBOLS: "600519,000858,300750,601318",
    AKSHARE_BRIDGE_URL: "http://127.0.0.1:8800",
    AKSHARE_BRIDGE_TOKEN: "",
    TRADING_STARTING_CASH: 1_000_000,
    TRADING_SEED_PORTFOLIO: true,
    MAX_ORDER_NOTIONAL: 100_000,
    MAX_POSITION_WEIGHT: 0.25,
    MAX_DAILY_LOSS: 0.05,
    COMMISSION_RATE: 0.0003,
    MIN_COMMISSION: 5,
    SLIPPAGE_BPS: 5,
    REAL_TRADING_ENABLED: false,
    STORE_BACKEND: "memory",
    DATA_DIR: "./data",
    CIRCUIT_MAX_CONSECUTIVE_LOSSES: 5,
    CIRCUIT_MAX_DAILY_DRAWDOWN: 0.08,
    CIRCUIT_COOLDOWN_MINUTES: 15,
    CIRCUIT_RECOVERY_MINUTES: 5,
    DYNAMIC_POSITION_SCALING: false,
    MAX_DRAWDOWN_REDUCTION_FACTOR: 0.25,
    ...overrides,
  };
}
